title = "Portfolio"
base_url = "https://brackenlo.github.io"

compile_sass = true
build_search_index = false

taxonomies = [{ name = "tags", feed = false }]

[markdown]
highlight_code = true

[extra]
