title = "Portfolio"
base_url = "127.0.0.1:1111"

compile_sass = true
build_search_index = false

taxonomies = [
  {name = "tags", feed = true},
  # {name = "tags", feed = true}
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
